### ISSUE TITLE
HTTPS on libusb.info is broken

### ISSUE THREAD

**Issue by neheb** [libusb/libusb.github.com#2]
Certificate points to GitHub. Speaking of which, https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by LudovicRousseau** [comment]
I updated the DNS records for libusb.info to point to 185.199.10x.153 IPs (instead of 192.30.252.153 and 192.30.252.154) as documented in https://help.github.com/articles/setting-up-an-apex-domain/

I will preform step 4 in a few days (after old DNS entries are expired)

**Comment by neheb** [comment]
Sweet. HTTPS seems to be working now. That was fast. Will close.

**Comment by LudovicRousseau** [comment]
I also enabled "Enforce HTTPS" as documented at https://help.github.com/articles/securing-your-github-pages-site-with-https/
This should not be a problem.
