### ISSUE TITLE
no alternative certificate subject name matches target host name 'www.libusb.info'

### ISSUE THREAD

**Issue by kucharskim** [libusb/libusb.github.com#3]
This is not a big deal and you probably are already aware of this, but reporting it anyway. Certificate for libusb.info doesn't cover www.libusb.info and when using domain with `www` prefix, loading page fails. See output of command `curl -v https://www.libusb.info` or:

```
openssl s_client \
  -servername www.libusb.info \
  -connect www.libusb.info:443 -showcerts < /dev/null | \
  openssl x509 -noout -text
```

versus

```
openssl s_client \
  -servername libusb.info \
  -connect libusb.info:443 -showcerts < /dev/null | \
  openssl x509 -noout -text
```

**Comment by LudovicRousseau** [comment]
Why do you want to use https://www.libusb.info ?
Do you get this URL from a libusb web page?

**Comment by kucharskim** [comment]
I don't think I've clicked on it via any link, but typed it by hand.

**Comment by mcuee** [comment]
Official website for libusb project is https://libusb.info/

**Comment by kucharskim** [comment]
Right, but would it be possible to add Subject Alternate Name to existing certificate for www.libusb.info when you have existing DNS record for www.libusb.info domain?

**Comment by LudovicRousseau** [comment]
The libusb web site (main page) is managed by github-pages and custom domain https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

If you can provide a patch for https://github.com/libusb/libusb.github.com to add www.libusb.info that would be fine.

**Comment by kucharskim** [comment]
Ok, after looking into this, the problem seems on the GitHub side and there is no straightforward solution, more details in isaacs/github#1675.

Some projects create a repo with a page content, where they setup `www.<domain>` via CNAME file and the page itself is just redirect to the main page at `<domain>` (which is hosted in different repo). So, two GitHub repos, one with main site, second repo with just a redirect.

Huh, that's so not optimal :|
